# Tokopedia Web Scraping

In [ ]:
import nbformat

nb = nbformat.read("/content/drive/MyDrive/Colab Notebooks/Project6_Tokopedia Web Scraping and Sentiment Analisis.ipynb", as_version=4)

if "widgets" in nb.metadata:
    del nb.metadata["widgets"]

nbformat.write(nb, "Project6_Tokopedia Web Scraping and Sentiment Analisis.ipynb")

In [1]:
from google.colab import drive
drive.mount('/content/drive') # Mount Google Drive to access files

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
! pip install selenium # Install Selenium library for web automation
! pip install webdriver_manager # Install webdriver_manager to automatically manage browser drivers
! pip install undetected_chromedriver # Install undetected_chromedriver for scraping websites that detect regular WebDriver

Collecting selenium
  Downloading selenium-4.45.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: certifi>=2026.2.25 in /usr/local/lib/python3.12/dist-packages (from selenium) (2026.5.20)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.15.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (26.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.18)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.45.0-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 83.8 MB/s eta 0:00:00
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.3/510.3 kB 48.6 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 15.8 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, urllib3, outcome, trio, trio-websocket, selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
Successfully installed outcome-1.3.0.post0 selenium-4.45.0 trio-0.33.0 trio-websocket-0.12.2 urllib3-2.7.0 wsproto-1.3.2
Collecting webdriver_manager
  Downloading webdriver_manager-4.1.2-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from webdriver_manager) (2.32.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from webdriver_manager) (1.2.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from webdriver_manager) (26.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver_manager) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver_manager) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver_manager) (2.7.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver_manager) (2026.5.20)
Downloading webdriver_manager-4.1.2-py3-none-any.whl (32 kB)
Installing collected packages: webdriver_manager
Successfully installed webdriver_manager-4.1.2
Collecting undetected_chromedriver
  Downloading undetected-chromedriver-3.5.5.tar.gz (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 kB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: selenium>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from undetected_chromedriver) (4.45.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from undetected_chromedriver) (2.32.4)
Requirement already satisfied: websockets in /usr/local/lib/python3.12/dist-packages (from undetected_chromedriver) (15.0.1)
Requirement already satisfied: certifi>=2026.2.25 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected_chromedriver) (2026.5.20)
Requirement already satisfied: trio<1.0,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected_chromedriver) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected_chromedriver) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected_chromedriver) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium>=4.9.0->undetected_chromedriver) (2.7.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected_chromedriver) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->undetected_chromedriver) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->undetected_chromedriver) (3.18)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected_chromedriver) (26.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected_chromedriver) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected_chromedriver) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected_chromedriver) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket<1.0,>=0.12.2->selenium>=4.9.0->undetected_chromedriver) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium>=4.9.0->undetected_chromedriver) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium>=4.9.0->undetected_chromedriver) (0.16.0)
Building wheels for collected packages: undetected_chromedriver
  Building wheel for undetected_chromedriver (setup.py) ... done
  Created wheel for undetected_chromedriver: filename=undetected_chromedriver-3.5.5-py3-none-any.whl size=47047 sha256=6ae1857026b2dbfb191c3b0d270c86c7f2f40501701050235e8930b30f4a925a
  Stored in directory: /root/.cache/pip/wheels/c4/f1/aa/9de6cf276210554d91e9c0526864563e850a428c5e76da4914
Successfully built undetected_chromedriver
Installing collected packages: undetected_chromedriver
Successfully installed undetected_chromedriver-3.5.5

In [13]:
from selenium import webdriver # Import webdriver from selenium
from selenium.webdriver.chrome.service import Service # Import Service to manage Chrome driver service
from webdriver_manager.chrome import ChromeDriverManager # Import ChromeDriverManager to install/manage Chrome driver
import time # Import time for delays
import undetected_chromedriver as uc # Import undetected_chromedriver for advanced scraping
from selenium.webdriver.common.by import By # Import By for locating elements
from selenium.webdriver.support.ui import WebDriverWait # Import WebDriverWait for explicit waits
from selenium.webdriver.support import expected_conditions as EC # Import expected_conditions for wait conditions

In [14]:
# Install Google Chrome Stable and its dependencies
!apt-get update
!wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
!echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google-chrome.list
!apt-get update
!apt-get install -y google-chrome-stable

# Setup WebDriver
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.binary_location = '/usr/bin/google-chrome'

# Initialize the Chrome driver, allowing ChromeDriverManager to find the correct version automatically
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

print("WebDriver initialized successfully in headless mode.")

Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:5 https://cli.github.com/packages stable InRelease [3,917 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:12 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,744 kB]
Get:13 https://cli.github.com/packages stable/main amd64 Packages [355 B]
Get:14 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,060 kB]
Get:15 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.4 MB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,611 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,357 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,489 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,221 kB]
Get:20 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,306 kB]
Get:21 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [4,024 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [82.8 kB]
Get:24 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.6 kB]
Fetched 42.7 MB in 12s (3,565 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Get:1 http://dl.google.com/linux/chrome/deb stable InRelease [1,825 B]
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://cli.github.com/packages stable InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:10 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,213 B]
Hit:11 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,038 B in 3s (871 B/s)
Reading package lists... Done
W: http://dl.google.com/linux/chrome/deb/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libvulkan1 libxcomposite1 libxtst6
  mesa-vulkan-drivers session-migration
The following NEW packages will be installed:
  at-spi2-core google-chrome-stable gsettings-desktop-schemas
  libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0 libvulkan1
  libxcomposite1 libxtst6 mesa-vulkan-drivers session-migration
0 upgraded, 12 newly installed, 0 to remove and 83 not upgraded.
Need to get 142 MB of archives.
After this operation, 475 MB of additional disk space will be used.
Get:1 http://dl.google.com/linux/chrome/deb stable/main amd64 google-chrome-stable amd64 149.0.7827.114-1 [130 MB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvulkan1 amd64 1.3.204.1-2 [128 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mesa-vulkan-drivers amd64 23.2.1-1ubuntu3.1~22.04.4 [10.7 MB]
Fetched 142 MB in 2s (78.8 MB/s)
Selecting previously unselected package libatk1.0-data.
(Reading database ... 122403 files and directories currently installed.)
Preparing to unpack .../00-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../01-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatspi2.0-0:amd64.
Preparing to unpack .../02-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../03-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libvulkan1:amd64.
Preparing to unpack .../04-libvulkan1_1.3.204.1-2_amd64.deb ...
Unpacking libvulkan1:amd64 (1.3.204.1-2) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../05-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package google-chrome-stable.
Preparing to unpack .../06-google-chrome-stable_149.0.7827.114-1_amd64.deb ...
Unpacking google-chrome-stable (149.0.7827.114-1) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../07-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../08-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../09-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../10-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package mesa-vulkan-drivers:amd64.
Preparing to unpack .../11-mesa-vulkan-drivers_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking mesa-vulkan-drivers:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libvulkan1:amd64 (1.3.204.1-2) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up mesa-vulkan-drivers:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up google-chrome-stable (149.0.7827.114-1) ...
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.9) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Setting up at-spi2-core (2.44.0-3) ...
WebDriver initialized successfully in headless mode.

In [15]:
import requests # Import requests library for making HTTP requests


def converted_shortlink(short_url):
  # Check if the URL is a Tokopedia shortlink
  if "tk.tokopedia.com" in short_url:
    # Define headers to mimic a web browser
    headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0 Safari/537.36"
    )
}

    # Make a GET request to the shortlink without following redirects
    res = requests.get(
      short_url,
      headers=headers,
      allow_redirects=False,
      timeout=10
)
    # Return the 'Location' header which contains the full URL
    return res.headers.get("Location")
  else:
    # If it's not a Tokopedia shortlink, return the original URL
    return short_url

In [16]:
import undetected_chromedriver as uc # Import undetected_chromedriver for advanced scraping
from selenium.webdriver.common.by import By # Import By for locating elements
import time # Import time for delays

def scraping_reviews(url):
    options = uc.ChromeOptions() # Create ChromeOptions object
    options.add_argument('--headless') # Run Chrome in headless mode (without a GUI)
    options.add_argument('--no-sandbox') # Bypass OS security model
    options.add_argument('--disable-dev-shm-usage') # Overcome limited resource problems
    # Tambahkan User-Agent agar lebih mirip manusia
    options.add_argument('--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')

    driver = uc.Chrome(options=options) # Initialize undetected_chromedriver
    driver.get(url) # Navigate to the given URL
    driver.implicitly_wait(10) # Set implicit wait for elements to be found

    reviews_data = [] # Initialize list to store review data


    # Get product name
    product_name = driver.find_element(By.CSS_SELECTOR, "h1[data-testid='lblPDPDetailProductName']")
    product_name = product_name.text # Extract text of product name
    print(f"Product Name: {product_name}") # Print product name

    try:
        # Scroll to make reviews visible (required on Tokopedia)
        driver.execute_script("window.scrollTo(0, 2000);")
        time.sleep(5) # Wait for content to load after scrolling

        # 1. Find ALL review containers (using 'article' tag or a wrapper class)
        # If data-testid 'unify-review-card' is not present, use the 'article' tag
        review_box = driver.find_elements(By.TAG_NAME, "article")

        print(f"Find {len(review_box)} review box(es).\n") # Print number of reviews found

        # 2. Iterate/Loop through each review box
        for box in review_box:
            try:
                # Get Name (search only within this 'box')
                name = box.find_element(By.CSS_SELECTOR, "span[class*='name']").text

                # Get Review Text
                review = box.find_element(By.CSS_SELECTOR, "span[data-testid='lblItemUlasan']").text

                # Get Stars from aria-label
                # Use a small try-except here in case a review has no stars
                try:
                    star_el = box.find_element(By.CSS_SELECTOR, "div[data-testid='icnStarRating']")
                    rating = star_el.get_attribute("aria-label") # Result: "bintang 5"
                except:
                    rating = "No Rating"

                # Add to list as a dictionary
                reviews_data.append({
                    "Name": name,
                    "Rating": rating,
                    "Review": review
                })

            except Exception as e:
                # If one review fails (e.g., an ad in between reviews), skip to the next review
                continue

    finally:
        driver.quit() # Close the browser when done or if an error occurs

    # Prepare the final JSON output structure
    hasil_json = {
    "Product": product_name,
    "Review": reviews_data
    }

    return hasil_json

In [17]:
# Convert the shortlink to a full URL
url = converted_shortlink("https://tk.tokopedia.com/ZSQqvqcxu/")
# Scrape all reviews from the URL
results = scraping_reviews(url)

Product Name: ACNAWAY Mugwort Gel Facial Wash Cleanser Acne Friendly Face Wash - Sabun Cuci Muka untuk Kulit Berjerawat & Sensitif Membersihkan Kotoran & Mencerahkan with Mugwort + Centella + Panthenol - Face Wash
Find 11 review box(es).

In [18]:
import json # Import the json library for working with JSON data

# Open a JSON file
with open("tokopedia_results.json", "w", encoding="utf-8") as f:
    json.dump(results, f, indent=2, ensure_ascii=False)

print("Successfully saved into JSON!") # Confirm that the file has been saved

Successfully saved into JSON!

In [19]:
json_text = json.dumps(results, indent=2, ensure_ascii=False) # Convert the 'results' dictionary to a formatted JSON string
print(json_text) # Print the JSON string

{
  "Product": "ACNAWAY Mugwort Gel Facial Wash Cleanser Acne Friendly Face Wash - Sabun Cuci Muka untuk Kulit Berjerawat & Sensitif Membersihkan Kotoran & Mencerahkan with Mugwort + Centella + Panthenol - Face Wash",
  "Review": [
    {
      "Name": "H***l",
      "Rating": "bintang 5",
      "Review": "Packingnya aman bgt..tebal bgt bubblewrapnya.. Wanginya soft enak.smoga cocok buat anakku Bahan: Mugwort dan centella Manfaat produk: Membersihkan muka Jenis kulit: Bermi..."
    },
    {
      "Name": "Y***o",
      "Rating": "bintang 5",
      "Review": "Pengiriman ny gercep,packing aman,buble wrape tebel bgt,nggak ada kebocoran,kekurangan. Produk ny baguss,cocok buat kulit sensitif"
    },
    {
      "Name": "U***h",
      "Rating": "bintang 5",
      "Review": "Mantul banget face wash nya, after nya bikin kulit ga ketarik, cocok buat aku yang acne prone skin dan beruntusan dikit, semoga cocok buat kedepannya dan bisa repurchase,..."
    },
    {
      "Name": "B***i",
      "Rating": "bintang 5",
      "Review": "Barang udah sampai dan kondisinya baik Bahan: Gentle di muka dan sejuk Manfaat produk: Mengurangi jerawat memperbaiki skin barrier Jenis kulit: Acne prone"
    },
    {
      "Name": "J***w",
      "Rating": "bintang 5",
      "Review": "beli yg ke 2, aku dpt rekomendasi dari temen dan bener ngurangin jerawat kecil kecil aku (ini gatel bgt) dan setelah pake acnaway combo ini ngefek bgt, tipkul aku jg yg c..."
    },
    {
      "Name": "M***z",
      "Rating": "bintang 5",
      "Review": "Maaf Bru ngulas soalnya mau nyoba dulu Alhamdulillah udh di coba baru 3hrian jerawat ku udh sedikit aga mendingan beruntusan juga hilang minusnya kalau abis cuci muka itu..."
    },
    {
      "Name": "D***r",
      "Rating": "bintang 5",
      "Review": "Packaging nya cakep rapih foll seriusan dh cocok nggk ny belakangan semoga ccok sh buat anak ku yg mudah beruntus😋🥰 tuk owner acnaway thankyou so much ya lancar selalu..."
    },
    {
      "Name": "T***h",
      "Rating": "bintang 5",
      "Review": "bagus,cocok untuk semua tipkul,rekomen buat tipkul berminyak/berjerawat"
    },
    {
      "Name": "H***e",
      "Rating": "bintang 5",
      "Review": "Beli untuk ke 2 kalinya karena pada saat itu breakout parah Karen pake pencuci produk sebelah dengan harga yang jauhh lebih mahal tapi alhasil jadi rusak pake ini agak me..."
    },
    {
      "Name": "C***o",
      "Rating": "bintang 5",
      "Review": "Order untuk yg ksekian kalinya , biasanya beli yg paketan ..soalnya semantul itu d wajah aku bantu bnget buat yg acneprone ini beli yg satuan soalnya stok Facialwash nya..."
    }
  ]
}

# Using Fine-Tuned Model for Sentiment Analysis

In [8]:
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification

model_name = "raissulaiman/indobert-tokopedia-sentiment"

tokenizer = AutoTokenizer.from_pretrained('indobenchmark/indobert-base-p1')
model = AutoModelForSequenceClassification.from_pretrained(model_name)

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [9]:
id2label = {0: "Negative", 1: "Positive"} # Map label IDs to sentiment strings
label2id = {"Negative": 0, "Positive": 1} # Map sentiment strings to label IDs



# Predicting example

In [10]:
from transformers import AutoTokenizer
import torch.nn.functional as F
import torch


#review example
review = "packing tidak aman, diterima dalam kondisi penyet"

print(f"Review: {review}")
# Set the model to evaluation mode
model.eval()
# Determine the device to use (GPU if available, otherwise CPU)
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
# Move the model to the selected device
model.to(device)

# Tokenize the input review: add padding, truncate to max_length, and return PyTorch tensors
inputs = tokenizer(review, padding=True, truncation=True, max_length=128, return_tensors='pt')
# Move the tokenized inputs to the selected device
inputs.to(device)

# Make a prediction using the model
logits = model(**inputs).logits
# Get the predicted label (index of the highest logit) for each input
labels = [torch.topk(logit, k=1, dim=-1)[1].squeeze().item() for logit in logits]
# Print the predicted sentiment label and its confidence score
print(f"{id2label[labels[0]]} ({F.softmax(logits[0], dim=-1).squeeze()[labels[0]] * 100:.3f}%)")

Review: packing tidak aman, diterima dalam kondisi penyet
Negative (99.897%)

# Data from scraping

In [20]:
import pandas as pd # Import pandas for data manipulation and analysis

df = pd.DataFrame(results["Review"]) # Create a pandas DataFrame from the 'ulasan' list in 'hasil'

# Add the product name as a new column to the DataFrame
df["Product"] = results["Product"]
df # Display the DataFrame

,Name,Rating,Review,Product
0,H***l,bintang 5,Packingnya aman bgt..tebal bgt bubblewrapnya.....,ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...
1,Y***o,bintang 5,"Pengiriman ny gercep,packing aman,buble wrape ...",ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...
2,U***h,bintang 5,"Mantul banget face wash nya, after nya bikin k...",ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...
3,B***i,bintang 5,Barang udah sampai dan kondisinya baik Bahan: ...,ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...
4,J***w,bintang 5,"beli yg ke 2, aku dpt rekomendasi dari temen d...",ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...
5,M***z,bintang 5,Maaf Bru ngulas soalnya mau nyoba dulu Alhamdu...,ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...
6,D***r,bintang 5,Packaging nya cakep rapih foll seriusan dh coc...,ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...
7,T***h,bintang 5,"bagus,cocok untuk semua tipkul,rekomen buat ti...",ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...
8,H***e,bintang 5,Beli untuk ke 2 kalinya karena pada saat itu b...,ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...
9,C***o,bintang 5,"Order untuk yg ksekian kalinya , biasanya beli...",ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...

In [21]:
for i in df['Review']:
  model.eval()
  device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
  model.to(device)

  inputs = tokenizer(i, padding=True, truncation=True, max_length=512, return_tensors='pt')
  inputs.to(device)

  # Make a prediction using the model
  logits = model(**inputs).logits
  # Get the predicted label (index of the highest logit) for each input
  labels = [torch.topk(logit, k=1, dim=-1)[1].squeeze().item() for logit in logits]
  # Add the predicted sentiment label to the DataFrame for the current review
  df.loc[df['Review'] == i, 'Sentiment'] = id2label[labels[0]]

df

,Name,Rating,Review,Product,Sentiment
0,H***l,bintang 5,Packingnya aman bgt..tebal bgt bubblewrapnya.....,ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...,Positive
1,Y***o,bintang 5,"Pengiriman ny gercep,packing aman,buble wrape ...",ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...,Positive
2,U***h,bintang 5,"Mantul banget face wash nya, after nya bikin k...",ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...,Positive
3,B***i,bintang 5,Barang udah sampai dan kondisinya baik Bahan: ...,ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...,Positive
4,J***w,bintang 5,"beli yg ke 2, aku dpt rekomendasi dari temen d...",ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...,Negative
5,M***z,bintang 5,Maaf Bru ngulas soalnya mau nyoba dulu Alhamdu...,ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...,Negative
6,D***r,bintang 5,Packaging nya cakep rapih foll seriusan dh coc...,ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...,Positive
7,T***h,bintang 5,"bagus,cocok untuk semua tipkul,rekomen buat ti...",ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...,Positive
8,H***e,bintang 5,Beli untuk ke 2 kalinya karena pada saat itu b...,ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...,Negative
9,C***o,bintang 5,"Order untuk yg ksekian kalinya , biasanya beli...",ACNAWAY Mugwort Gel Facial Wash Cleanser Acne ...,Negative

In [22]:
json_nested = {
    "Product": df["Product"].iloc[0], # Get the product name from the first row of the 'produk' column
    "Review": df.drop(columns="Product").to_dict(orient="records") # Convert the DataFrame (excluding 'produk' column) to a list of dictionaries
}

In [23]:
print(json_nested) # Print the nested JSON structure

{'Product': 'ACNAWAY Mugwort Gel Facial Wash Cleanser Acne Friendly Face Wash - Sabun Cuci Muka untuk Kulit Berjerawat & Sensitif Membersihkan Kotoran & Mencerahkan with Mugwort + Centella + Panthenol - Face Wash', 'Review': [{'Name': 'H***l', 'Rating': 'bintang 5', 'Review': 'Packingnya aman bgt..tebal bgt bubblewrapnya.. Wanginya soft enak.smoga cocok buat anakku Bahan: Mugwort dan centella Manfaat produk: Membersihkan muka Jenis kulit: Bermi...', 'Sentiment': 'Positive'}, {'Name': 'Y***o', 'Rating': 'bintang 5', 'Review': 'Pengiriman ny gercep,packing aman,buble wrape tebel bgt,nggak ada kebocoran,kekurangan. Produk ny baguss,cocok buat kulit sensitif', 'Sentiment': 'Positive'}, {'Name': 'U***h', 'Rating': 'bintang 5', 'Review': 'Mantul banget face wash nya, after nya bikin kulit ga ketarik, cocok buat aku yang acne prone skin dan beruntusan dikit, semoga cocok buat kedepannya dan bisa repurchase,...', 'Sentiment': 'Positive'}, {'Name': 'B***i', 'Rating': 'bintang 5', 'Review': 'Barang udah sampai dan kondisinya baik Bahan: Gentle di muka dan sejuk Manfaat produk: Mengurangi jerawat memperbaiki skin barrier Jenis kulit: Acne prone', 'Sentiment': 'Positive'}, {'Name': 'J***w', 'Rating': 'bintang 5', 'Review': 'beli yg ke 2, aku dpt rekomendasi dari temen dan bener ngurangin jerawat kecil kecil aku (ini gatel bgt) dan setelah pake acnaway combo ini ngefek bgt, tipkul aku jg yg c...', 'Sentiment': 'Negative'}, {'Name': 'M***z', 'Rating': 'bintang 5', 'Review': 'Maaf Bru ngulas soalnya mau nyoba dulu Alhamdulillah udh di coba baru 3hrian jerawat ku udh sedikit aga mendingan beruntusan juga hilang minusnya kalau abis cuci muka itu...', 'Sentiment': 'Negative'}, {'Name': 'D***r', 'Rating': 'bintang 5', 'Review': 'Packaging nya cakep rapih foll seriusan dh cocok nggk ny belakangan semoga ccok sh buat anak ku yg mudah beruntus😋🥰 tuk owner acnaway thankyou so much ya lancar selalu...', 'Sentiment': 'Positive'}, {'Name': 'T***h', 'Rating': 'bintang 5', 'Review': 'bagus,cocok untuk semua tipkul,rekomen buat tipkul berminyak/berjerawat', 'Sentiment': 'Positive'}, {'Name': 'H***e', 'Rating': 'bintang 5', 'Review': 'Beli untuk ke 2 kalinya karena pada saat itu breakout parah Karen pake pencuci produk sebelah dengan harga yang jauhh lebih mahal tapi alhasil jadi rusak pake ini agak me...', 'Sentiment': 'Negative'}, {'Name': 'C***o', 'Rating': 'bintang 5', 'Review': 'Order untuk yg ksekian kalinya , biasanya beli yg paketan ..soalnya semantul itu d wajah aku bantu bnget buat yg acneprone ini beli yg satuan soalnya stok Facialwash nya...', 'Sentiment': 'Negative'}]}